// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Student.proto

package com.codebasket.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentToOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.StudentTo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    java.util.List<com.codebasket.proto.StudentProto.SubjectTo> 
        getSubjectsList();
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    com.codebasket.proto.StudentProto.SubjectTo getSubjects(int index);
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    int getSubjectsCount();
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    java.util.List<? extends com.codebasket.proto.StudentProto.SubjectToOrBuilder> 
        getSubjectsOrBuilderList();
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    com.codebasket.proto.StudentProto.SubjectToOrBuilder getSubjectsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.StudentTo}
   */
  public  static final class StudentTo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.StudentTo)
      StudentToOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentTo.newBuilder() to construct.
    private StudentTo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentTo() {
      id_ = 0;
      name_ = "";
      email_ = "";
      subjects_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentTo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                subjects_ = new java.util.ArrayList<com.codebasket.proto.StudentProto.SubjectTo>();
                mutable_bitField0_ |= 0x00000008;
              }
              subjects_.add(
                  input.readMessage(com.codebasket.proto.StudentProto.SubjectTo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          subjects_ = java.util.Collections.unmodifiableList(subjects_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebasket.proto.StudentProto.internal_static_model_StudentTo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebasket.proto.StudentProto.internal_static_model_StudentTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebasket.proto.StudentProto.StudentTo.class, com.codebasket.proto.StudentProto.StudentTo.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECTS_FIELD_NUMBER = 4;
    private java.util.List<com.codebasket.proto.StudentProto.SubjectTo> subjects_;
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    public java.util.List<com.codebasket.proto.StudentProto.SubjectTo> getSubjectsList() {
      return subjects_;
    }
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    public java.util.List<? extends com.codebasket.proto.StudentProto.SubjectToOrBuilder> 
        getSubjectsOrBuilderList() {
      return subjects_;
    }
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    public int getSubjectsCount() {
      return subjects_.size();
    }
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    public com.codebasket.proto.StudentProto.SubjectTo getSubjects(int index) {
      return subjects_.get(index);
    }
    /**
     * <code>repeated .model.SubjectTo subjects = 4;</code>
     */
    public com.codebasket.proto.StudentProto.SubjectToOrBuilder getSubjectsOrBuilder(
        int index) {
      return subjects_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < subjects_.size(); i++) {
        output.writeMessage(4, subjects_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < subjects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, subjects_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.codebasket.proto.StudentProto.StudentTo)) {
        return super.equals(obj);
      }
      com.codebasket.proto.StudentProto.StudentTo other = (com.codebasket.proto.StudentProto.StudentTo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getSubjectsList()
          .equals(other.getSubjectsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getSubjectsCount() > 0) {
        hash = (37 * hash) + SUBJECTS_FIELD_NUMBER;
        hash = (53 * hash) + getSubjectsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.StudentTo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.codebasket.proto.StudentProto.StudentTo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.StudentTo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.StudentTo)
        com.codebasket.proto.StudentProto.StudentToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codebasket.proto.StudentProto.internal_static_model_StudentTo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codebasket.proto.StudentProto.internal_static_model_StudentTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codebasket.proto.StudentProto.StudentTo.class, com.codebasket.proto.StudentProto.StudentTo.Builder.class);
      }

      // Construct using com.codebasket.proto.StudentProto.StudentTo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubjectsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        if (subjectsBuilder_ == null) {
          subjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          subjectsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codebasket.proto.StudentProto.internal_static_model_StudentTo_descriptor;
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.StudentTo getDefaultInstanceForType() {
        return com.codebasket.proto.StudentProto.StudentTo.getDefaultInstance();
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.StudentTo build() {
        com.codebasket.proto.StudentProto.StudentTo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.StudentTo buildPartial() {
        com.codebasket.proto.StudentProto.StudentTo result = new com.codebasket.proto.StudentProto.StudentTo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        if (subjectsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            subjects_ = java.util.Collections.unmodifiableList(subjects_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.subjects_ = subjects_;
        } else {
          result.subjects_ = subjectsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codebasket.proto.StudentProto.StudentTo) {
          return mergeFrom((com.codebasket.proto.StudentProto.StudentTo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codebasket.proto.StudentProto.StudentTo other) {
        if (other == com.codebasket.proto.StudentProto.StudentTo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (subjectsBuilder_ == null) {
          if (!other.subjects_.isEmpty()) {
            if (subjects_.isEmpty()) {
              subjects_ = other.subjects_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureSubjectsIsMutable();
              subjects_.addAll(other.subjects_);
            }
            onChanged();
          }
        } else {
          if (!other.subjects_.isEmpty()) {
            if (subjectsBuilder_.isEmpty()) {
              subjectsBuilder_.dispose();
              subjectsBuilder_ = null;
              subjects_ = other.subjects_;
              bitField0_ = (bitField0_ & ~0x00000008);
              subjectsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubjectsFieldBuilder() : null;
            } else {
              subjectsBuilder_.addAllMessages(other.subjects_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codebasket.proto.StudentProto.StudentTo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codebasket.proto.StudentProto.StudentTo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.codebasket.proto.StudentProto.SubjectTo> subjects_ =
        java.util.Collections.emptyList();
      private void ensureSubjectsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          subjects_ = new java.util.ArrayList<com.codebasket.proto.StudentProto.SubjectTo>(subjects_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.codebasket.proto.StudentProto.SubjectTo, com.codebasket.proto.StudentProto.SubjectTo.Builder, com.codebasket.proto.StudentProto.SubjectToOrBuilder> subjectsBuilder_;

      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public java.util.List<com.codebasket.proto.StudentProto.SubjectTo> getSubjectsList() {
        if (subjectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subjects_);
        } else {
          return subjectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public int getSubjectsCount() {
        if (subjectsBuilder_ == null) {
          return subjects_.size();
        } else {
          return subjectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public com.codebasket.proto.StudentProto.SubjectTo getSubjects(int index) {
        if (subjectsBuilder_ == null) {
          return subjects_.get(index);
        } else {
          return subjectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder setSubjects(
          int index, com.codebasket.proto.StudentProto.SubjectTo value) {
        if (subjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectsIsMutable();
          subjects_.set(index, value);
          onChanged();
        } else {
          subjectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder setSubjects(
          int index, com.codebasket.proto.StudentProto.SubjectTo.Builder builderForValue) {
        if (subjectsBuilder_ == null) {
          ensureSubjectsIsMutable();
          subjects_.set(index, builderForValue.build());
          onChanged();
        } else {
          subjectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder addSubjects(com.codebasket.proto.StudentProto.SubjectTo value) {
        if (subjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectsIsMutable();
          subjects_.add(value);
          onChanged();
        } else {
          subjectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder addSubjects(
          int index, com.codebasket.proto.StudentProto.SubjectTo value) {
        if (subjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectsIsMutable();
          subjects_.add(index, value);
          onChanged();
        } else {
          subjectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder addSubjects(
          com.codebasket.proto.StudentProto.SubjectTo.Builder builderForValue) {
        if (subjectsBuilder_ == null) {
          ensureSubjectsIsMutable();
          subjects_.add(builderForValue.build());
          onChanged();
        } else {
          subjectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder addSubjects(
          int index, com.codebasket.proto.StudentProto.SubjectTo.Builder builderForValue) {
        if (subjectsBuilder_ == null) {
          ensureSubjectsIsMutable();
          subjects_.add(index, builderForValue.build());
          onChanged();
        } else {
          subjectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder addAllSubjects(
          java.lang.Iterable<? extends com.codebasket.proto.StudentProto.SubjectTo> values) {
        if (subjectsBuilder_ == null) {
          ensureSubjectsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subjects_);
          onChanged();
        } else {
          subjectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder clearSubjects() {
        if (subjectsBuilder_ == null) {
          subjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          subjectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public Builder removeSubjects(int index) {
        if (subjectsBuilder_ == null) {
          ensureSubjectsIsMutable();
          subjects_.remove(index);
          onChanged();
        } else {
          subjectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public com.codebasket.proto.StudentProto.SubjectTo.Builder getSubjectsBuilder(
          int index) {
        return getSubjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public com.codebasket.proto.StudentProto.SubjectToOrBuilder getSubjectsOrBuilder(
          int index) {
        if (subjectsBuilder_ == null) {
          return subjects_.get(index);  } else {
          return subjectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public java.util.List<? extends com.codebasket.proto.StudentProto.SubjectToOrBuilder> 
           getSubjectsOrBuilderList() {
        if (subjectsBuilder_ != null) {
          return subjectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subjects_);
        }
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public com.codebasket.proto.StudentProto.SubjectTo.Builder addSubjectsBuilder() {
        return getSubjectsFieldBuilder().addBuilder(
            com.codebasket.proto.StudentProto.SubjectTo.getDefaultInstance());
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public com.codebasket.proto.StudentProto.SubjectTo.Builder addSubjectsBuilder(
          int index) {
        return getSubjectsFieldBuilder().addBuilder(
            index, com.codebasket.proto.StudentProto.SubjectTo.getDefaultInstance());
      }
      /**
       * <code>repeated .model.SubjectTo subjects = 4;</code>
       */
      public java.util.List<com.codebasket.proto.StudentProto.SubjectTo.Builder> 
           getSubjectsBuilderList() {
        return getSubjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.codebasket.proto.StudentProto.SubjectTo, com.codebasket.proto.StudentProto.SubjectTo.Builder, com.codebasket.proto.StudentProto.SubjectToOrBuilder> 
          getSubjectsFieldBuilder() {
        if (subjectsBuilder_ == null) {
          subjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.codebasket.proto.StudentProto.SubjectTo, com.codebasket.proto.StudentProto.SubjectTo.Builder, com.codebasket.proto.StudentProto.SubjectToOrBuilder>(
                  subjects_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          subjects_ = null;
        }
        return subjectsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.StudentTo)
    }

    // @@protoc_insertion_point(class_scope:model.StudentTo)
    private static final com.codebasket.proto.StudentProto.StudentTo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.codebasket.proto.StudentProto.StudentTo();
    }

    public static com.codebasket.proto.StudentProto.StudentTo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentTo>
        PARSER = new com.google.protobuf.AbstractParser<StudentTo>() {
      @java.lang.Override
      public StudentTo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentTo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentTo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentTo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.codebasket.proto.StudentProto.StudentTo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubjectToOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.SubjectTo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subject = 1;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>string subject = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();
  }
  /**
   * Protobuf type {@code model.SubjectTo}
   */
  public  static final class SubjectTo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.SubjectTo)
      SubjectToOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubjectTo.newBuilder() to construct.
    private SubjectTo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubjectTo() {
      subject_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubjectTo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codebasket.proto.StudentProto.internal_static_model_SubjectTo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codebasket.proto.StudentProto.internal_static_model_SubjectTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codebasket.proto.StudentProto.SubjectTo.class, com.codebasket.proto.StudentProto.SubjectTo.Builder.class);
    }

    public static final int SUBJECT_FIELD_NUMBER = 1;
    private volatile java.lang.Object subject_;
    /**
     * <code>string subject = 1;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <code>string subject = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subject_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subject_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.codebasket.proto.StudentProto.SubjectTo)) {
        return super.equals(obj);
      }
      com.codebasket.proto.StudentProto.SubjectTo other = (com.codebasket.proto.StudentProto.SubjectTo) obj;

      boolean result = true;
      result = result && getSubject()
          .equals(other.getSubject());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.codebasket.proto.StudentProto.SubjectTo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.codebasket.proto.StudentProto.SubjectTo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.SubjectTo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.SubjectTo)
        com.codebasket.proto.StudentProto.SubjectToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codebasket.proto.StudentProto.internal_static_model_SubjectTo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codebasket.proto.StudentProto.internal_static_model_SubjectTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codebasket.proto.StudentProto.SubjectTo.class, com.codebasket.proto.StudentProto.SubjectTo.Builder.class);
      }

      // Construct using com.codebasket.proto.StudentProto.SubjectTo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subject_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codebasket.proto.StudentProto.internal_static_model_SubjectTo_descriptor;
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.SubjectTo getDefaultInstanceForType() {
        return com.codebasket.proto.StudentProto.SubjectTo.getDefaultInstance();
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.SubjectTo build() {
        com.codebasket.proto.StudentProto.SubjectTo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.codebasket.proto.StudentProto.SubjectTo buildPartial() {
        com.codebasket.proto.StudentProto.SubjectTo result = new com.codebasket.proto.StudentProto.SubjectTo(this);
        result.subject_ = subject_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codebasket.proto.StudentProto.SubjectTo) {
          return mergeFrom((com.codebasket.proto.StudentProto.SubjectTo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codebasket.proto.StudentProto.SubjectTo other) {
        if (other == com.codebasket.proto.StudentProto.SubjectTo.getDefaultInstance()) return this;
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codebasket.proto.StudentProto.SubjectTo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codebasket.proto.StudentProto.SubjectTo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <code>string subject = 1;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subject = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subject = 1;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 1;</code>
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 1;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.SubjectTo)
    }

    // @@protoc_insertion_point(class_scope:model.SubjectTo)
    private static final com.codebasket.proto.StudentProto.SubjectTo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.codebasket.proto.StudentProto.SubjectTo();
    }

    public static com.codebasket.proto.StudentProto.SubjectTo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubjectTo>
        PARSER = new com.google.protobuf.AbstractParser<SubjectTo>() {
      @java.lang.Override
      public SubjectTo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubjectTo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubjectTo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubjectTo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.codebasket.proto.StudentProto.SubjectTo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_StudentTo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_StudentTo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_SubjectTo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_SubjectTo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/Student.proto\022\005model\"X\n\tStud" +
      "entTo\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email" +
      "\030\003 \001(\t\022\"\n\010subjects\030\004 \003(\0132\020.model.Subject" +
      "To\"\034\n\tSubjectTo\022\017\n\007subject\030\001 \001(\tB$\n\024com." +
      "codebasket.protoB\014StudentProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_StudentTo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_StudentTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_StudentTo_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Subjects", });
    internal_static_model_SubjectTo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_SubjectTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_SubjectTo_descriptor,
        new java.lang.String[] { "Subject", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
